# Generated by Django 2.2.1 on 2019-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_returngift'),
    ]

    operations = [
        migrations.AddField(
            model_name='returngift',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
    ]
