# Generated by Django 2.2.1 on 2019-06-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hydmrgbachelorparty_hydmrgfood_hydmrggifts_hydmrghalls_hydmrgmandapdecoration_hydmrgsangeethdecorati'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='person',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
