# Generated by Django 2.2.1 on 2019-06-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190607_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='person',
            field=models.CharField(max_length=20),
        ),
    ]
